# Generated by Django 3.2.13 on 2023-02-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Kamentariya', 'verbose_name_plural': 'Kamentariyalar'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': "Rasm / 'Images' ", 'verbose_name_plural': "Rasmlar / 'Images'"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': "Maxsulotlar So'zlamasi", 'verbose_name_plural': "Maxsulotlar So'zlamalari"},
        ),
        migrations.AlterModelOptions(
            name='productlang',
            options={'verbose_name': 'Maxsulot Tili', 'verbose_name_plural': 'Maxslotlar Tillari'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size'},
        ),
    ]
