# Generated by Django 3.2.13 on 2023-03-11 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Brand Havolasi'),
            preserve_default=False,
        ),
    ]
