# Generated by Django 3.2.13 on 2023-03-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230312_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFuture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=50)),
                ('qiymat', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Maxsulot xaqida xarakteristika',
                'verbose_name_plural': 'Maxsulotlar xaqida',
            },
        ),
    ]
