# Generated by Django 3.2.13 on 2023-02-20 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=56, verbose_name='Brand Nomi: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(upload_to='images/brands', verbose_name='Brand Rasmi: '),
        ),
    ]
