# Generated by Django 3.2.13 on 2023-03-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='images/banners-home/%Y/%m/%d', verbose_name='Banner Rasmi'),
        ),
    ]
