# Generated by Django 3.2.13 on 2023-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default=1049, max_length=56, verbose_name='Banner Nomi: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='images/banners-home', verbose_name='Banner Rasmi'),
        ),
    ]
