# Generated by Django 3.2.13 on 2023-04-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230409_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Maxsulot', 'verbose_name_plural': 'Maxsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
    ]
